### ISSUE TITLE
不能多服务器回应

### ISSUE THREAD

**Issue by ZEERDEER** [bboysoulcn/telemonitor#2]
我在不同的服务器上用 docker-compose 部署了，设置的同一个 Telegram bot 只能显示一个服务器。
希望后续能更新，谢谢你的项目

**Comment by bboysoulcn** [comment]
> 我在不同的服务器上用 docker-compose 部署了，设置的同一个 Telegram bot 只能显示一个服务器。 希望后续能更新，谢谢你的项目

之后会考虑多台服务器的
