### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by wxyShine** [bboysoulcn/telemonitor#3]
感觉可以增加个ssh登录提醒  怎么样？

**Comment by bboysoulcn** [comment]
> 感觉可以增加个ssh登录提醒 怎么样？

good idea

**Comment by bboysoulcn** [comment]
> 感觉可以增加个ssh登录提醒 怎么样？

不过貌似只能通过监控日志来做，这个不同系统日志名字不一样，日志内容也不一样，不是很优雅，目前不会考虑
