### ISSUE TITLE
项目起不来=-=求助

### ISSUE THREAD

**Issue by ghost** [bboysoulcn/telemonitor#4]
docker-compose up -d之后拉取镜像很卡 我使用的是阿里云的镜像源
然后只需要修改的是docker-compose.yaml文件中的  
- TG_CHAT_ID=your_chat_id
 - TG_API_TOKEN=your_api_token 
 - 改成自己的id和token是吗。
我是第一次跑github的项目 求助

**Comment by bboysoulcn** [comment]
> docker-compose up -d之后拉取镜像很卡 我使用的是阿里云的镜像源
> 
> 然后只需要修改的是docker-compose.yaml文件中的  
> 
> - TG_CHAT_ID=your_chat_id
> 
>  - TG_API_TOKEN=your_api_token 
> 
>  - 改成自己的id和token是吗。
> 
> 我是第一次跑github的项目 求助

对的
